Add delete  message API function
GNUWeeb/GNUWeebBot pull request #27
Opened 2021-05-07 16:59 UTC by shashi918

Signed-off-by: shashi918 <sr0298037@gmail.com>

Added delete message API

2021-05-07 17:02 UTC, ammarfaizi2 commented on src/gwbot/include/gwbot/lib/tg_api/delete_message.h
> +int tga_delete_chat(tga_handle_t *handle, const tga_delete_chat_t *ctx);
```suggestion
int tga_delete_msg(tga_handle_t *handle, const tga_delete_msg_t *ctx);
```

2021-05-07 17:04 UTC, ammarfaizi2 commented
Please fix it based on the code review above.

2021-05-07 17:28 UTC, ammarfaizi2 commented on src/gwbot/lib/tg_api/delete_message.c
> +
Remove this unnecessary whitespace

2021-05-07 17:29 UTC, ammarfaizi2 commented
Bad indentation and whitespace.
Don't use spaces for struct indentation. Use tabs.

2021-05-07 17:30 UTC, ammarfaizi2 commented
Remove unnecessary whitespace in delete_message.c line 21.

2021-05-07 17:38 UTC, shashi918 commented on src/gwbot/include/gwbot/lib/tg_api/delete_message.h
> +        uint64_t        message_id;
![image](https://user-images.githubusercontent.com/68495300/117487734-17d2bf80-af89-11eb-95b3-10c951c2b4dd.png)

here showing fine why?

2021-05-07 17:40 UTC, shashi918 commented on src/gwbot/lib/tg_api/delete_message.c
> +
ok fixing the white spaces  problem

2021-05-07 17:59 UTC, ammarfaizi2 commented on src/gwbot/include/gwbot/lib/tg_api/delete_message.h
> +        uint64_t        message_id;
They are not tabs.

2021-05-08 04:45 UTC, ammarfaizi2 requested changes

2021-05-08 04:45 UTC, ammarfaizi2 commented on src/gwbot/lib/tg_api/delete_message.c
> +	tga_set_method(handle,"deleteMessage");
Put space after comma

2021-05-08 11:28 UTC, closed without merging